### ISSUE TITLE
how to set time label?

### ISSUE THREAD

**Issue by bill-bil** [infinum/flutter-charts#21]
hi :
    how to set axis-x time label  
![image](https://user-images.githubusercontent.com/74221254/137622697-834e0c07-3ed8-48b7-bcdb-0b63233298f2.png)

**Comment by bill-gege** [comment]
Thank you very much !That's great !

**Comment by persilee** [comment]
@bill-bil  你好：

我们发现你的GitHub上的项目 ebank_enterprise 是我们公司的商务项目，我是本项目的创建人之一，请您尽快在GitHub上删除此项目，谢谢！

否则，我司将走法律途径！

有问题，可随时联系我。
我的联系方式：
电话：13006610162
微信号：per_lsy


@bill-bil  Hello:

We found your project ebank_enterprise on GitHub is a business project of our company, I am one of the creators of this project, please delete this project on GitHub as soon as possible, thank you!

Otherwise, our company will take legal way!

If you have any questions, you can contact me anytime.
my contact information:
Tel: 13006610162
WeChat ID: per_lsy
